from distutils.core import setup
setup(
  name = 'RailsDates',
  packages = ['RailsDates'],
  version = '0.5',
  license='MIT',
  description = 'A library that allows Python devs to mimic the useful date methods available in Ruby on Rails.',
  author = 'KayLa Thomas',
  author_email = 'kaylathomas.dev@gmail.com',
  url = 'https://github.com/kaylathomas/RailsDates',
  download_url = 'https://github.com/kaylathomas/RailsDates/archive/refs/tags/v_0.5.tar.gz',
  keywords = ['ruby on rails', 'ruby', 'python', 'date library'],
  install_requires=[],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
  ],
)