
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T14:41:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddb57c9d443e25a1d4bc1e429dffed110accb7dd",
 "version": "2023.11.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
