# coding: utf-8

"""
    Snowflake Database API

    The Snowflake Database API is a REST API that you can use to access, update, and perform certain actions on Database resource in Snowflake.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.database._generated
from snowflake.core.database._generated.models.clone import Clone  # noqa: E501
from snowflake.core.database._generated.rest import ApiException

class TestClone(unittest.TestCase):
    """Clone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Clone
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Clone`
        """
        model = snowflake.core.database._generated.models.clone.Clone()  # noqa: E501
        if include_optional :
            return Clone(
                source = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_', 
                point_of_time = snowflake.core.database._generated.models.point_of_time.PointOfTime(
                    point_of_time_type = '', 
                    reference = '', 
                    when = '', )
            )
        else :
            return Clone(
                source = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_',
        )
        """

    def testClone(self):
        """Test Clone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
