#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class KafkaMessageType(Enum):
    EXPRESSION = "EXPRESSION"
    INPUT = "INPUT"
    STATE = "STATE"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "KafkaMessageType":
        return cls.MISSING_ENUM
