#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class KqiSourceOrderField(Enum):
    CREATED_AT = "CREATED_AT"
    NAME = "NAME"
    UPDATED_AT = "UPDATED_AT"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "KqiSourceOrderField":
        return cls.MISSING_ENUM
