#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class TransfStrategy(Enum):
    MERGE = "MERGE"
    REPLACE = "REPLACE"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "TransfStrategy":
        return cls.MISSING_ENUM
