#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class VariableType(Enum):
    DATE = "DATE"
    INT = "INT"
    LOCATION = "LOCATION"
    PROJECT = "PROJECT"
    STRING = "STRING"
    USER = "USER"
    WORK_ORDER = "WORK_ORDER"
    WORK_ORDER_TYPE = "WORK_ORDER_TYPE"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "VariableType":
        return cls.MISSING_ENUM
