
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-13T01:31:33-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "635b33b90f32aee9776cbc98f6a83a2d09c00ff4",
 "version": "0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
