# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caikit_data_model.common.runtime.runtimeinforequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9caikit_data_model.common.runtime.runtimeinforequest.proto\x12 caikit_data_model.common.runtime\"\x14\n\x12RuntimeInfoRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'caikit_data_model.common.runtime.runtimeinforequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RUNTIMEINFOREQUEST']._serialized_start=95
  _globals['_RUNTIMEINFOREQUEST']._serialized_end=115
# @@protoc_insertion_point(module_scope)
