# coding: utf-8

"""
    Snowflake Schema API

    The Snowflake Schema API is a REST API that you can use to access, update, and perform certain actions on Schema resource in Snowflake.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.schema._generated
from snowflake.core.schema._generated.models.clone_time_travel import CloneTimeTravel  # noqa: E501
from snowflake.core.schema._generated.rest import ApiException

class TestCloneTimeTravel(unittest.TestCase):
    """CloneTimeTravel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CloneTimeTravel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CloneTimeTravel`
        """
        model = snowflake.core.schema._generated.models.clone_time_travel.CloneTimeTravel()  # noqa: E501
        if include_optional :
            return CloneTimeTravel(
                when = '', 
                point_of_time = None
            )
        else :
            return CloneTimeTravel(
        )
        """

    def testCloneTimeTravel(self):
        """Test CloneTimeTravel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
