
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-18T14:22:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "75f83314aa2c03b8ef831e7d527b4fb93ad049e0",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
