# coding: utf-8

"""
    Snowflake Table API

    The Snowflake Table API is a REST API that you can use to access, update, and perform certain actions on Tables resource in a Snowflake database.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.table._generated
from snowflake.core.table._generated.models.constraint_model import ConstraintModel  # noqa: E501
from snowflake.core.table._generated.rest import ApiException

class TestConstraintModel(unittest.TestCase):
    """ConstraintModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConstraintModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConstraintModel`
        """
        model = snowflake.core.table._generated.models.constraint_model.ConstraintModel()  # noqa: E501
        if include_optional :
            return ConstraintModel(
                name = '', 
                column_names = [
                    ''
                    ], 
                constraint_type = ''
            )
        else :
            return ConstraintModel(
        )
        """

    def testConstraintModel(self):
        """Test ConstraintModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
