
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-17T11:04:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "404d674960239610e4aaa54bffece2ec2d697ff1",
 "version": "8.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
