
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T18:14:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "612b20ee6b1bce87d0d7333a0a4a68abc6e8119b",
 "version": "2.9.17.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
