#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from ..input.base_block_input import BaseBlockInput
from ..input.block_u_i_representation_input import BlockUIRepresentationInput
from ..input.decision_route_input import DecisionRouteInput
from ..input.entry_point_input import EntryPointInput
from ..input.exit_point_input import ExitPointInput


@dataclass(frozen=True)
class ChoiceBlockInput(DataClassJsonMixin):
    basicDefinitions: BaseBlockInput
    cid: str
    routes: List[DecisionRouteInput]
    defaultExitPoint: Optional[ExitPointInput] = None
    entryPoint: Optional[EntryPointInput] = None
    uiRepresentation: Optional[BlockUIRepresentationInput] = None
