#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from gql_client.runtime.enum_utils import enum_field_metadata
from ..enum.kafka_message_type import KafkaMessageType

from ..input.base_block_input import BaseBlockInput
from ..input.block_u_i_representation_input import BlockUIRepresentationInput
from ..input.entry_point_input import EntryPointInput
from ..input.exit_point_input import ExitPointInput


@dataclass(frozen=True)
class KafkaBlockInput(DataClassJsonMixin):
    basicDefinitions: BaseBlockInput
    brokers: List[str]
    cid: str
    message: str
    topic: str
    type: KafkaMessageType = _field(metadata=enum_field_metadata(KafkaMessageType))
    entryPoint: Optional[EntryPointInput] = None
    exitPoint: Optional[ExitPointInput] = None
    uiRepresentation: Optional[BlockUIRepresentationInput] = None
