
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-17T21:20:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2809ef78deda5d8e990173c5265475a257a387da",
 "version": "3.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
