# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2023-11-08T03:50:32+00:00

from __future__ import annotations

from kelvin.sdk.client.data_model import DataModelBase


class TimeMicro(DataModelBase):
    """
    TimeMicro object.

    Parameters
    ----------

    """
