from .files import reg
from .files import SOM
from .files import SOMDATA
from .files import primitive
from .files import defuzz
from .files import genetic
from .files import sugeno
from .files import pso
from .files import mamdani
from .files import primhard
from .files import dir
from .files import mamdaniweigths
from .files import SLP
from .files import sugenoweight
from .files import defuzzt