
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-10T17:47:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "80b086f34ab6634d19c041c264f173858a0ab669",
 "version": "23.08.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
