# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kerfed/protos/common/v1/shop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kerfed.protos.common.v1 import money_pb2 as kerfed_dot_protos_dot_common_dot_v1_dot_money__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"kerfed/protos/common/v1/shop.proto\x12\x17kerfed.protos.common.v1\x1a#kerfed/protos/common/v1/money.proto\"n\n\x07KFactor\x12\x1f\n\x0bmaterial_id\x18\x01 \x01(\tR\nmaterialId\x12\'\n\x0fradius_fraction\x18\x02 \x03(\x01R\x0eradiusFraction\x12\x19\n\x08k_factor\x18\x03 \x03(\x01R\x07kFactor\"T\n\x15ManufacturingSettings\x12;\n\x08k_factor\x18\x04 \x03(\x0b\x32 .kerfed.protos.common.v1.KFactorR\x07kFactor\"\x8d\x02\n\x12\x44isbursementPolicy\x12\x1f\n\x0b\x66\x65\x65_percent\x18\x01 \x01(\x01R\nfeePercent\x12;\n\tfee_fixed\x18\x02 \x01(\x0b\x32\x1e.kerfed.protos.common.v1.MoneyR\x08\x66\x65\x65\x46ixed\x12?\n\x0b\x66\x65\x65_monthly\x18\x03 \x01(\x0b\x32\x1e.kerfed.protos.common.v1.MoneyR\nfeeMonthly\x12\x1d\n\ncc_percent\x18\x04 \x01(\x01R\tccPercent\x12\x39\n\x08\x63\x63_fixed\x18\x05 \x01(\x0b\x32\x1e.kerfed.protos.common.v1.MoneyR\x07\x63\x63\x46ixedB\xe2\x01\n\x1b\x63om.kerfed.protos.common.v1B\tShopProtoP\x01Z9github.com/kerfed/protos/kerfed/protos/common/v1;commonv1\xa2\x02\x03KPC\xaa\x02\x17Kerfed.Protos.Common.V1\xca\x02\x17Kerfed\\Protos\\Common\\V1\xe2\x02#Kerfed\\Protos\\Common\\V1\\GPBMetadata\xea\x02\x1aKerfed::Protos::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kerfed.protos.common.v1.shop_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.kerfed.protos.common.v1B\tShopProtoP\001Z9github.com/kerfed/protos/kerfed/protos/common/v1;commonv1\242\002\003KPC\252\002\027Kerfed.Protos.Common.V1\312\002\027Kerfed\\Protos\\Common\\V1\342\002#Kerfed\\Protos\\Common\\V1\\GPBMetadata\352\002\032Kerfed::Protos::Common::V1'
  _globals['_KFACTOR']._serialized_start=100
  _globals['_KFACTOR']._serialized_end=210
  _globals['_MANUFACTURINGSETTINGS']._serialized_start=212
  _globals['_MANUFACTURINGSETTINGS']._serialized_end=296
  _globals['_DISBURSEMENTPOLICY']._serialized_start=299
  _globals['_DISBURSEMENTPOLICY']._serialized_end=568
# @@protoc_insertion_point(module_scope)
