
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T01:06:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a7110d177051ac757deb8234ce6b25d32a5bac2",
 "version": "1.9.9.post0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
