# Generated by Django 4.2.3 on 2023-10-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ge", "0006_alter_logs_igem_version_alter_wfcontrol_igem_version"),
        ("omics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assembly", models.CharField(max_length=20)),
                ("gene_id", models.IntegerField()),
                ("symbol", models.CharField(max_length=50)),
                ("chromosome", models.IntegerField()),
                ("nucleotide_version", models.CharField(max_length=50)),
                ("start_position", models.IntegerField()),
                ("end_position", models.IntegerField()),
                ("orientation", models.CharField(max_length=1)),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ge.term",
                    ),
                ),
            ],
        ),
    ]
