
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-16T14:28:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7005708c4fc7b3aeffaeddbacc002d6d8e644e78",
 "version": "2023.11.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
