
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T06:38:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8db1e866488ddeb1ede8a951c6ee035b0eb4e37e",
 "version": "1.1.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
