
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-18T00:06:47-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "d38d6491fc58326fd0ef3c6d47e2763cf1d0bdcf",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
