
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T20:26:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a782ab0f23dae54fed2d531cafa9e0a3f4ca03e2",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
