
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T17:16:03+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "a882d99514d6347787d3e084df7ababf60320856",
 "version": "1.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
