#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class DiscoveryMethod(Enum):
    INVENTORY = "INVENTORY"
    MANUAL = "MANUAL"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "DiscoveryMethod":
        return cls.MISSING_ENUM
