#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class GoToType(Enum):
    DESTINATION = "DESTINATION"
    ORIGIN = "ORIGIN"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "GoToType":
        return cls.MISSING_ENUM
