#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class RetryUnit(Enum):
    HOURS = "HOURS"
    MINUTES = "MINUTES"
    SECONDS = "SECONDS"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "RetryUnit":
        return cls.MISSING_ENUM
