#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class ServiceStatus(Enum):
    DISCONNECTED = "DISCONNECTED"
    IN_SERVICE = "IN_SERVICE"
    MAINTENANCE = "MAINTENANCE"
    PENDING = "PENDING"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "ServiceStatus":
        return cls.MISSING_ENUM
