#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class SurveyStatus(Enum):
    COMPLETED = "COMPLETED"
    INPROGRESS = "INPROGRESS"
    PLANNED = "PLANNED"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "SurveyStatus":
        return cls.MISSING_ENUM
