from .files import factorial
from .files import aplha_e
from .files import palindrome
from .files import palf
from .files import armstrong
from .files import ULW_spaces
from .files import alphabetic_order
from .files import count
from .files import replace
from .files import largest
from .files import frequency
from .files import duplicates
from .files import random_list
from .files import reverse_list 
from .files import dict_1 
from .files import dict_2
from .files import dict_3
from .files import dict_4
from .files import cp_reverse
from .files import cp_reverse
from .files import vowels_extract
from .files import rectangle
from .files import payroll
from .files import salary_calculate
from .files import daily_week_worker
from .files import image_play
from .files import turtle_indian
from .files import turtle_house
from .files import gui_calc
from .files import gui_reg
from .files import dir