
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T15:06:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f0da4ece913a5898a04a8bbd3172fce2ec54814",
 "version": "2023.11.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
