
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-19T08:41:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f0f2d68e232ed826e33d75b30db6a0255ec9f46",
 "version": "0.7.0.post0.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
