
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T15:17:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6decfdada33505b9a27e3837cda183b73ba9ab79",
 "version": "2.6.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
