# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import client_pb2 as apps_dot_picture__service_dot_client__pb2


class PictureStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDemotivator = channel.unary_unary(
                '/pictures.Picture/CreateDemotivator',
                request_serializer=apps_dot_picture__service_dot_client__pb2.DemotivatorRequest.SerializeToString,
                response_deserializer=apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.FromString,
                )
        self.CreateDemotivatorTemplate = channel.unary_unary(
                '/pictures.Picture/CreateDemotivatorTemplate',
                request_serializer=apps_dot_picture__service_dot_client__pb2.DemotivatorTemplateRequest.SerializeToString,
                response_deserializer=apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.FromString,
                )
        self.ResizeImage = channel.unary_unary(
                '/pictures.Picture/ResizeImage',
                request_serializer=apps_dot_picture__service_dot_client__pb2.ResizeImageRequest.SerializeToString,
                response_deserializer=apps_dot_picture__service_dot_client__pb2.ResizeImageResponse.FromString,
                )
        self.CreateJpeg = channel.unary_unary(
                '/pictures.Picture/CreateJpeg',
                request_serializer=apps_dot_picture__service_dot_client__pb2.JpegRequest.SerializeToString,
                response_deserializer=apps_dot_picture__service_dot_client__pb2.JpegResponse.FromString,
                )
        self.CreateMessageFrameDemotivator = channel.unary_unary(
                '/pictures.Picture/CreateMessageFrameDemotivator',
                request_serializer=apps_dot_picture__service_dot_client__pb2.MessageFrameDemotivatorRequest.SerializeToString,
                response_deserializer=apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.FromString,
                )


class PictureServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDemotivator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDemotivatorTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJpeg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessageFrameDemotivator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PictureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDemotivator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDemotivator,
                    request_deserializer=apps_dot_picture__service_dot_client__pb2.DemotivatorRequest.FromString,
                    response_serializer=apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.SerializeToString,
            ),
            'CreateDemotivatorTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDemotivatorTemplate,
                    request_deserializer=apps_dot_picture__service_dot_client__pb2.DemotivatorTemplateRequest.FromString,
                    response_serializer=apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.SerializeToString,
            ),
            'ResizeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeImage,
                    request_deserializer=apps_dot_picture__service_dot_client__pb2.ResizeImageRequest.FromString,
                    response_serializer=apps_dot_picture__service_dot_client__pb2.ResizeImageResponse.SerializeToString,
            ),
            'CreateJpeg': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJpeg,
                    request_deserializer=apps_dot_picture__service_dot_client__pb2.JpegRequest.FromString,
                    response_serializer=apps_dot_picture__service_dot_client__pb2.JpegResponse.SerializeToString,
            ),
            'CreateMessageFrameDemotivator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessageFrameDemotivator,
                    request_deserializer=apps_dot_picture__service_dot_client__pb2.MessageFrameDemotivatorRequest.FromString,
                    response_serializer=apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pictures.Picture', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Picture(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDemotivator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pictures.Picture/CreateDemotivator',
            apps_dot_picture__service_dot_client__pb2.DemotivatorRequest.SerializeToString,
            apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDemotivatorTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pictures.Picture/CreateDemotivatorTemplate',
            apps_dot_picture__service_dot_client__pb2.DemotivatorTemplateRequest.SerializeToString,
            apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResizeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pictures.Picture/ResizeImage',
            apps_dot_picture__service_dot_client__pb2.ResizeImageRequest.SerializeToString,
            apps_dot_picture__service_dot_client__pb2.ResizeImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateJpeg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pictures.Picture/CreateJpeg',
            apps_dot_picture__service_dot_client__pb2.JpegRequest.SerializeToString,
            apps_dot_picture__service_dot_client__pb2.JpegResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMessageFrameDemotivator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pictures.Picture/CreateMessageFrameDemotivator',
            apps_dot_picture__service_dot_client__pb2.MessageFrameDemotivatorRequest.SerializeToString,
            apps_dot_picture__service_dot_client__pb2.DemotivatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
