# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apps/picture-service/client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!apps/picture-service/client.proto\x12\x08pictures\"z\n\x1eMessageFrameDemotivatorRequest\x12\x14\n\x0c\x61vatar_bytes\x18\x01 \x01(\x0c\x12\x14\n\x0cmessage_text\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65motivator_text\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\"\"\n\x0bJpegRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\"4\n\x0cJpegResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\"H\n\x12ResizeImageRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\";\n\x13ResizeImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\"*\n\x1a\x44\x65motivatorTemplateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"7\n\x12\x44\x65motivatorRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x0c\n\x04text\x18\x02 \x01(\t\";\n\x13\x44\x65motivatorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\x32\xb0\x03\n\x07Picture\x12P\n\x11\x43reateDemotivator\x12\x1c.pictures.DemotivatorRequest\x1a\x1d.pictures.DemotivatorResponse\x12`\n\x19\x43reateDemotivatorTemplate\x12$.pictures.DemotivatorTemplateRequest\x1a\x1d.pictures.DemotivatorResponse\x12J\n\x0bResizeImage\x12\x1c.pictures.ResizeImageRequest\x1a\x1d.pictures.ResizeImageResponse\x12;\n\nCreateJpeg\x12\x15.pictures.JpegRequest\x1a\x16.pictures.JpegResponse\x12h\n\x1d\x43reateMessageFrameDemotivator\x12(.pictures.MessageFrameDemotivatorRequest\x1a\x1d.pictures.DemotivatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apps.picture_service.client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEFRAMEDEMOTIVATORREQUEST']._serialized_start=47
  _globals['_MESSAGEFRAMEDEMOTIVATORREQUEST']._serialized_end=169
  _globals['_JPEGREQUEST']._serialized_start=171
  _globals['_JPEGREQUEST']._serialized_end=205
  _globals['_JPEGRESPONSE']._serialized_start=207
  _globals['_JPEGRESPONSE']._serialized_end=259
  _globals['_RESIZEIMAGEREQUEST']._serialized_start=261
  _globals['_RESIZEIMAGEREQUEST']._serialized_end=333
  _globals['_RESIZEIMAGERESPONSE']._serialized_start=335
  _globals['_RESIZEIMAGERESPONSE']._serialized_end=394
  _globals['_DEMOTIVATORTEMPLATEREQUEST']._serialized_start=396
  _globals['_DEMOTIVATORTEMPLATEREQUEST']._serialized_end=438
  _globals['_DEMOTIVATORREQUEST']._serialized_start=440
  _globals['_DEMOTIVATORREQUEST']._serialized_end=495
  _globals['_DEMOTIVATORRESPONSE']._serialized_start=497
  _globals['_DEMOTIVATORRESPONSE']._serialized_end=556
  _globals['_PICTURE']._serialized_start=559
  _globals['_PICTURE']._serialized_end=991
# @@protoc_insertion_point(module_scope)
