"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MessageFrameDemotivatorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AVATAR_BYTES_FIELD_NUMBER: builtins.int
    MESSAGE_TEXT_FIELD_NUMBER: builtins.int
    DEMOTIVATOR_TEXT_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    avatar_bytes: builtins.bytes
    message_text: builtins.str
    demotivator_text: builtins.str
    first_name: builtins.str
    def __init__(
        self,
        *,
        avatar_bytes: builtins.bytes = ...,
        message_text: builtins.str = ...,
        demotivator_text: builtins.str = ...,
        first_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["avatar_bytes", b"avatar_bytes", "demotivator_text", b"demotivator_text", "first_name", b"first_name", "message_text", b"message_text"]) -> None: ...

global___MessageFrameDemotivatorRequest = MessageFrameDemotivatorRequest

@typing_extensions.final
class JpegRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_BYTES_FIELD_NUMBER: builtins.int
    image_bytes: builtins.bytes
    def __init__(
        self,
        *,
        image_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_bytes", b"image_bytes"]) -> None: ...

global___JpegRequest = JpegRequest

@typing_extensions.final
class JpegResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    IMAGE_BYTES_FIELD_NUMBER: builtins.int
    success: builtins.bool
    image_bytes: builtins.bytes
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        image_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_bytes", b"image_bytes", "success", b"success"]) -> None: ...

global___JpegResponse = JpegResponse

@typing_extensions.final
class ResizeImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_BYTES_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    image_bytes: builtins.bytes
    height: builtins.int
    width: builtins.int
    def __init__(
        self,
        *,
        image_bytes: builtins.bytes = ...,
        height: builtins.int = ...,
        width: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["height", b"height", "image_bytes", b"image_bytes", "width", b"width"]) -> None: ...

global___ResizeImageRequest = ResizeImageRequest

@typing_extensions.final
class ResizeImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    IMAGE_BYTES_FIELD_NUMBER: builtins.int
    success: builtins.bool
    image_bytes: builtins.bytes
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        image_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_bytes", b"image_bytes", "success", b"success"]) -> None: ...

global___ResizeImageResponse = ResizeImageResponse

@typing_extensions.final
class DemotivatorTemplateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    text: builtins.str
    def __init__(
        self,
        *,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["text", b"text"]) -> None: ...

global___DemotivatorTemplateRequest = DemotivatorTemplateRequest

@typing_extensions.final
class DemotivatorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_BYTES_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    image_bytes: builtins.bytes
    text: builtins.str
    def __init__(
        self,
        *,
        image_bytes: builtins.bytes = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_bytes", b"image_bytes", "text", b"text"]) -> None: ...

global___DemotivatorRequest = DemotivatorRequest

@typing_extensions.final
class DemotivatorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    IMAGE_BYTES_FIELD_NUMBER: builtins.int
    success: builtins.bool
    image_bytes: builtins.bytes
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        image_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image_bytes", b"image_bytes", "success", b"success"]) -> None: ...

global___DemotivatorResponse = DemotivatorResponse
