
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T11:09:54-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ebd34d9e64624d0b43bd7cfe317b46b14d8578b",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
