
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T20:21:54+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "32b26f890eadae5bf6c53be0153e2bcc1a7906e1",
 "version": "v0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
