
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-17T11:49:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c372445d760dbd709e6458d6ba8ad7ca1928d38",
 "version": "1.8.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
