
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-17T20:17:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3d6368e07bfd3c3b27d5eeb42361a8b14b14345",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
