# coding: utf-8

"""
    Snowflake Compute Pools API

    The Snowflake Compute Pools API is a REST API that you can use to access, update, and perform certain actions on Compute Pool resources.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import snowflake.core.compute_pool._generated
from snowflake.core.compute_pool._generated.api.compute_pool_api import ComputePoolApi  # noqa: E501
from snowflake.core.compute_pool._generated.api_client import BridgeApiClient
from snowflake.core.compute_pool._generated.rest import ApiException

from typing import Dict, List, Optional


class TestComputePoolApi(unittest.TestCase):
    """ComputePoolApi unit test stubs"""

    def setUp(self):
        self.api = snowflake.core.compute_pool._generated.api.compute_pool_api.ComputePoolApi(BridgeApiClient())  # noqa: E501

    def tearDown(self):
        pass

    def test_create_compute_pool(self):
        """Test case for create_compute_pool

        Create a compute pool  # noqa: E501
        """
        pass

    def test_create_or_alter_compute_pool(self):
        """Test case for create_or_alter_compute_pool

        Create a (or alter an existing) compute pool.  # noqa: E501
        """
        pass

    def test_delete_compute_pool(self):
        """Test case for delete_compute_pool

        Delete a compute pool  # noqa: E501
        """
        pass

    def test_fetch_compute_pool(self):
        """Test case for fetch_compute_pool

        Fetch a compute pool.  # noqa: E501
        """
        pass

    def test_fetch_compute_pools(self):
        """Test case for fetch_compute_pools

        List compute pools  # noqa: E501
        """
        pass

    def test_resume_compute_pool(self):
        """Test case for resume_compute_pool

        Resume a compute pool  # noqa: E501
        """
        pass

    def test_stop_all_services_in_compute_pool(self):
        """Test case for stop_all_services_in_compute_pool

        Stops all services on the compute pool.  # noqa: E501
        """
        pass

    def test_suspend_compute_pool(self):
        """Test case for suspend_compute_pool

        Perform an action on a compute pool  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
