# coding: utf-8

"""
    Snowflake Compute Pools API

    The Snowflake Compute Pools API is a REST API that you can use to access, update, and perform certain actions on Compute Pool resources.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.compute_pool._generated
from snowflake.core.compute_pool._generated.models.compute_pool import ComputePool  # noqa: E501
from snowflake.core.compute_pool._generated.rest import ApiException

class TestComputePool(unittest.TestCase):
    """ComputePool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComputePool
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComputePool`
        """
        model = snowflake.core.compute_pool._generated.models.compute_pool.ComputePool()  # noqa: E501
        if include_optional :
            return ComputePool(
                name = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_', 
                warehouse = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_', 
                min_nodes = 56, 
                max_nodes = 56, 
                instance_family = '', 
                auto_resume = True, 
                comment = '', 
                state = 'UNKNOWN', 
                num_services = 56, 
                auto_suspend_secs = 56, 
                active_nodes = 56, 
                idle_nodes = 56, 
                created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                resumed_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                owner = ''
            )
        else :
            return ComputePool(
                name = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_',
                min_nodes = 56,
                max_nodes = 56,
                instance_family = '',
        )
        """

    def testComputePool(self):
        """Test ComputePool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
