# coding: utf-8

"""
    Snowflake Compute Pools API

    The Snowflake Compute Pools API is a REST API that you can use to access, update, and perform certain actions on Compute Pool resources.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.compute_pool._generated
from snowflake.core.compute_pool._generated.models.fetch_compute_pools_show_limit_parameter import FetchComputePoolsShowLimitParameter  # noqa: E501
from snowflake.core.compute_pool._generated.rest import ApiException

class TestFetchComputePoolsShowLimitParameter(unittest.TestCase):
    """FetchComputePoolsShowLimitParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FetchComputePoolsShowLimitParameter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchComputePoolsShowLimitParameter`
        """
        model = snowflake.core.compute_pool._generated.models.fetch_compute_pools_show_limit_parameter.FetchComputePoolsShowLimitParameter()  # noqa: E501
        if include_optional :
            return FetchComputePoolsShowLimitParameter(
                rows = 56, 
                name_string = ''
            )
        else :
            return FetchComputePoolsShowLimitParameter(
                rows = 56,
        )
        """

    def testFetchComputePoolsShowLimitParameter(self):
        """Test FetchComputePoolsShowLimitParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
