
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T04:46:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2f3ead5667691913cd7285ebf0c4037bbb28442",
 "version": "1.19.1.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
