# coding: utf-8

"""
    Snowflake Database API

    The Snowflake Database API is a REST API that you can use to access, update, and perform certain actions on Database resource in Snowflake.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import snowflake.core.database._generated
from snowflake.core.database._generated.api.database_api import DatabaseApi  # noqa: E501
from snowflake.core.database._generated.api_client import BridgeApiClient
from snowflake.core.database._generated.rest import ApiException

from typing import Dict, List, Optional


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self):
        self.api = snowflake.core.database._generated.api.database_api.DatabaseApi(BridgeApiClient())  # noqa: E501

    def tearDown(self):
        pass

    def test_create_database(self):
        """Test case for create_database

        Create a database  # noqa: E501
        """
        pass

    def test_create_database_from_share(self):
        """Test case for create_database_from_share

        Create a database from a share.  # noqa: E501
        """
        pass

    def test_create_or_update_database(self):
        """Test case for create_or_update_database

        Create a (or alter an existing) database.  # noqa: E501
        """
        pass

    def test_delete_database(self):
        """Test case for delete_database

        Delete a database.  # noqa: E501
        """
        pass

    def test_disable_database_failover(self):
        """Test case for disable_database_failover

        Disable database failover.  # noqa: E501
        """
        pass

    def test_disable_database_replication(self):
        """Test case for disable_database_replication

        Disable database replication.  # noqa: E501
        """
        pass

    def test_enable_database_failover(self):
        """Test case for enable_database_failover

        Enable database failover.  # noqa: E501
        """
        pass

    def test_enable_database_replication(self):
        """Test case for enable_database_replication

        Enable database replication.  # noqa: E501
        """
        pass

    def test_fetch_database(self):
        """Test case for fetch_database

        """
        pass

    def test_list_databases(self):
        """Test case for list_databases

        List databases  # noqa: E501
        """
        pass

    def test_primary_database_failover(self):
        """Test case for primary_database_failover

        Set database as primary.  # noqa: E501
        """
        pass

    def test_refresh_database_replication(self):
        """Test case for refresh_database_replication

        Refresh database replications.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
