# coding: utf-8

"""
    Snowflake Database API

    The Snowflake Database API is a REST API that you can use to access, update, and perform certain actions on Database resource in Snowflake.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.database._generated
from snowflake.core.database._generated.models.database import Database  # noqa: E501
from snowflake.core.database._generated.rest import ApiException

class TestDatabase(unittest.TestCase):
    """Database unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Database
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Database`
        """
        model = snowflake.core.database._generated.models.database.Database()  # noqa: E501
        if include_optional :
            return Database(
                created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                name = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_', 
                is_default = True, 
                is_current = True, 
                origin = '', 
                owner = '', 
                comment = '', 
                options = '', 
                dropped_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                data_retention_time_in_days = 56, 
                default_ddl_collation = '', 
                log_level = '', 
                max_data_extension_time_in_days = 56, 
                suspend_task_after_num_failures = 56, 
                trace_level = '', 
                user_task_managed_initial_warehouse_size = '', 
                user_task_timeout_ms = 56
            )
        else :
            return Database(
                name = '_AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_',
        )
        """

    def testDatabase(self):
        """Test Database"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
