# coding: utf-8

"""
    Snowflake Database API

    The Snowflake Database API is a REST API that you can use to access, update, and perform certain actions on Database resource in Snowflake.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.database._generated
from snowflake.core.database._generated.models.point_of_time import PointOfTime  # noqa: E501
from snowflake.core.database._generated.rest import ApiException

class TestPointOfTime(unittest.TestCase):
    """PointOfTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PointOfTime
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PointOfTime`
        """
        model = snowflake.core.database._generated.models.point_of_time.PointOfTime()  # noqa: E501
        if include_optional :
            return PointOfTime(
                point_of_time_type = '', 
                reference = '', 
                when = ''
            )
        else :
            return PointOfTime(
                point_of_time_type = '',
        )
        """

    def testPointOfTime(self):
        """Test PointOfTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
