#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from gql_client.runtime.enum_utils import enum_field_metadata
from ..enum.image_entity import ImageEntity


@dataclass(frozen=True)
class AddImageInput(DataClassJsonMixin):
    contentType: str
    entityId: str
    entityType: ImageEntity = _field(metadata=enum_field_metadata(ImageEntity))
    fileName: str
    fileSize: int
    imgKey: str
    modified: datetime = _field(metadata=config(encoder=custom_scalars["Time"].encoder, decoder=custom_scalars["Time"].decoder, mm_field=custom_scalars["Time"].mm_field))
    annotation: Optional[str] = None
    category: Optional[str] = None
    createTime: Optional[datetime] = None
    documentCategoryId: Optional[str] = None
    latitude: Optional[Number] = None
    longitude: Optional[Number] = None
