#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from ..input.check_list_definition_input import CheckListDefinitionInput


@dataclass(frozen=True)
class CheckListCategoryDefinitionInput(DataClassJsonMixin):
    checkList: List[CheckListDefinitionInput]
    title: str
    description: Optional[str] = None
    id: Optional[str] = None
