#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from gql_client.runtime.enum_utils import enum_field_metadata
from ..enum.auth_type import AuthType
from ..enum.url_method import UrlMethod

from ..input.base_block_input import BaseBlockInput
from ..input.block_u_i_representation_input import BlockUIRepresentationInput
from ..input.entry_point_input import EntryPointInput
from ..input.exit_point_input import ExitPointInput
from ..input.variable_expression_input import VariableExpressionInput


@dataclass(frozen=True)
class InvokeRestAPIBlockInput(DataClassJsonMixin):
    basicDefinitions: BaseBlockInput
    body: str
    cid: str
    connectionTimeOut: int
    method: UrlMethod = _field(metadata=enum_field_metadata(UrlMethod))
    params: List[VariableExpressionInput]
    url: str
    authType: Optional[AuthType] = None
    clientId: Optional[str] = None
    clientSecret: Optional[str] = None
    entryPoint: Optional[EntryPointInput] = None
    exitPoint: Optional[ExitPointInput] = None
    headers: Optional[str] = None
    oidcUrl: Optional[str] = None
    password: Optional[str] = None
    uiRepresentation: Optional[BlockUIRepresentationInput] = None
    user: Optional[str] = None
