# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.classificationprediction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import classinfo_pb2 as watson__nlp__data__model_dot_classinfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4watson_nlp_data_model.classificationprediction.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a%watson_nlp_data_model.classinfo.proto\"\x88\x01\n\x18\x43lassificationPrediction\x12\x31\n\x07\x63lasses\x18\x01 \x03(\x0b\x32 .watson_nlp_data_model.ClassInfo\x12\x39\n\x0bproducer_id\x18\x02 \x01(\x0b\x32$.caikit_data_model.common.ProducerIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.classificationprediction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLASSIFICATIONPREDICTION']._serialized_start=162
  _globals['_CLASSIFICATIONPREDICTION']._serialized_end=298
# @@protoc_insertion_point(module_scope)
