# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.concept.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#watson_nlp_data_model.concept.proto\x12\x15watson_nlp_data_model\"D\n\x07\x43oncept\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\trelevance\x18\x02 \x01(\x01\x12\x18\n\x10\x64\x62pedia_resource\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.concept_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONCEPT']._serialized_start=62
  _globals['_CONCEPT']._serialized_end=130
# @@protoc_insertion_point(module_scope)
