# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.conversationinput.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from watson_nlp_data_model import conversationutterance_pb2 as watson__nlp__data__model_dot_conversationutterance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-watson_nlp_data_model.conversationinput.proto\x12\x15watson_nlp_data_model\x1a\x31watson_nlp_data_model.conversationutterance.proto\"p\n\x11\x43onversationInput\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x42\n\x0c\x63onversation\x18\x02 \x03(\x0b\x32,.watson_nlp_data_model.ConversationUtteranceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.conversationinput_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONVERSATIONINPUT']._serialized_start=123
  _globals['_CONVERSATIONINPUT']._serialized_end=235
# @@protoc_insertion_point(module_scope)
