# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.dependency.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from watson_nlp_data_model import dependencyrelation_pb2 as watson__nlp__data__model_dot_dependencyrelation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&watson_nlp_data_model.dependency.proto\x12\x15watson_nlp_data_model\x1a.watson_nlp_data_model.dependencyrelation.proto\"y\n\nDependency\x12;\n\x08relation\x18\x01 \x01(\x0e\x32).watson_nlp_data_model.DependencyRelation\x12\x12\n\nidentifier\x18\x02 \x01(\r\x12\x11\n\x04head\x18\x03 \x01(\rH\x00\x88\x01\x01\x42\x07\n\x05_headb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.dependency_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEPENDENCY']._serialized_start=113
  _globals['_DEPENDENCY']._serialized_end=234
# @@protoc_insertion_point(module_scope)
