# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.detagprediction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import htmltagspanslist_pb2 as watson__nlp__data__model_dot_htmltagspanslist__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+watson_nlp_data_model.detagprediction.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a,watson_nlp_data_model.htmltagspanslist.proto\"\xdd\x02\n\x0f\x44\x65tagPrediction\x12\x0c\n\x04html\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07offsets\x18\x03 \x03(\x03\x12\x13\n\x0btag_offsets\x18\x04 \x03(\x03\x12W\n\x12tag_names_to_spans\x18\x05 \x03(\x0b\x32;.watson_nlp_data_model.DetagPrediction.TagNamesToSpansEntry\x12>\n\x0bproducer_id\x18\x06 \x01(\x0b\x32$.caikit_data_model.common.ProducerIdH\x00\x88\x01\x01\x1a_\n\x14TagNamesToSpansEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.watson_nlp_data_model.HTMLTagSpansList:\x02\x38\x01\x42\x0e\n\x0c_producer_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.detagprediction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _DETAGPREDICTION_TAGNAMESTOSPANSENTRY._options = None
  _DETAGPREDICTION_TAGNAMESTOSPANSENTRY._serialized_options = b'8\001'
  _globals['_DETAGPREDICTION']._serialized_start=160
  _globals['_DETAGPREDICTION']._serialized_end=509
  _globals['_DETAGPREDICTION_TAGNAMESTOSPANSENTRY']._serialized_start=398
  _globals['_DETAGPREDICTION_TAGNAMESTOSPANSENTRY']._serialized_end=493
# @@protoc_insertion_point(module_scope)
