# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.embedding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import densematrix_pb2 as watson__nlp__data__model_dot_densematrix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%watson_nlp_data_model.embedding.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a\'watson_nlp_data_model.densematrix.proto\"\x97\x02\n\tEmbedding\x12\x30\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\".watson_nlp_data_model.DenseMatrix\x12\x46\n\x0cvocab_to_idx\x18\x02 \x03(\x0b\x32\x30.watson_nlp_data_model.Embedding.VocabToIdxEntry\x12\x39\n\x0bproducer_id\x18\x03 \x01(\x0b\x32$.caikit_data_model.common.ProducerId\x12\x10\n\x08pad_word\x18\x04 \x01(\t\x12\x10\n\x08unk_word\x18\x05 \x01(\t\x1a\x31\n\x0fVocabToIdxEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.embedding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _EMBEDDING_VOCABTOIDXENTRY._options = None
  _EMBEDDING_VOCABTOIDXENTRY._serialized_options = b'8\001'
  _globals['_EMBEDDING']._serialized_start=149
  _globals['_EMBEDDING']._serialized_end=428
  _globals['_EMBEDDING_VOCABTOIDXENTRY']._serialized_start=379
  _globals['_EMBEDDING_VOCABTOIDXENTRY']._serialized_end=428
# @@protoc_insertion_point(module_scope)
