# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.entitiesprediction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import entity_pb2 as watson__nlp__data__model_dot_entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.watson_nlp_data_model.entitiesprediction.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a\"watson_nlp_data_model.entity.proto\"\x80\x01\n\x12\x45ntitiesPrediction\x12/\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x1d.watson_nlp_data_model.Entity\x12\x39\n\x0bproducer_id\x18\x02 \x01(\x0b\x32$.caikit_data_model.common.ProducerIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.entitiesprediction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTITIESPREDICTION']._serialized_start=153
  _globals['_ENTITIESPREDICTION']._serialized_end=281
# @@protoc_insertion_point(module_scope)
