# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.entitymentionclass.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.watson_nlp_data_model.entitymentionclass.proto\x12\x15watson_nlp_data_model*R\n\x12\x45ntityMentionClass\x12\x0f\n\x0bMENTC_UNSET\x10\x00\x12\r\n\tMENTC_SPC\x10\x01\x12\r\n\tMENTC_NEG\x10\x02\x12\r\n\tMENTC_GEN\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.entitymentionclass_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTITYMENTIONCLASS']._serialized_start=73
  _globals['_ENTITYMENTIONCLASS']._serialized_end=155
# @@protoc_insertion_point(module_scope)
