# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.entitymention.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import entitymentionclass_pb2 as watson__nlp__data__model_dot_entitymentionclass__pb2
from watson_nlp_data_model import entitymentiontype_pb2 as watson__nlp__data__model_dot_entitymentiontype__pb2
from watson_nlp_data_model import span_pb2 as watson__nlp__data__model_dot_span__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)watson_nlp_data_model.entitymention.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a.watson_nlp_data_model.entitymentionclass.proto\x1a-watson_nlp_data_model.entitymentiontype.proto\x1a watson_nlp_data_model.span.proto\"\xa7\x02\n\rEntityMention\x12)\n\x04span\x18\x01 \x01(\x0b\x32\x1b.watson_nlp_data_model.Span\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x39\n\x0bproducer_id\x18\x03 \x01(\x0b\x32$.caikit_data_model.common.ProducerId\x12\x12\n\nconfidence\x18\x04 \x01(\x01\x12>\n\x0cmention_type\x18\x05 \x01(\x0e\x32(.watson_nlp_data_model.EntityMentionType\x12@\n\rmention_class\x18\x06 \x01(\x0e\x32).watson_nlp_data_model.EntityMentionClass\x12\x0c\n\x04role\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.entitymention_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTITYMENTION']._serialized_start=241
  _globals['_ENTITYMENTION']._serialized_end=536
# @@protoc_insertion_point(module_scope)
