# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.propertylistvaluespan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from watson_nlp_data_model import span_pb2 as watson__nlp__data__model_dot_span__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1watson_nlp_data_model.propertylistvaluespan.proto\x12\x15watson_nlp_data_model\x1a watson_nlp_data_model.span.proto\"A\n\x15PropertyListValueSpan\x12(\n\x03val\x18\x01 \x03(\x0b\x32\x1b.watson_nlp_data_model.Spanb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.propertylistvaluespan_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROPERTYLISTVALUESPAN']._serialized_start=110
  _globals['_PROPERTYLISTVALUESPAN']._serialized_end=175
# @@protoc_insertion_point(module_scope)
