# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.relation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from watson_nlp_data_model import entity_pb2 as watson__nlp__data__model_dot_entity__pb2
from watson_nlp_data_model import relationmention_pb2 as watson__nlp__data__model_dot_relationmention__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$watson_nlp_data_model.relation.proto\x12\x15watson_nlp_data_model\x1a\"watson_nlp_data_model.entity.proto\x1a+watson_nlp_data_model.relationmention.proto\"\xcf\x01\n\x08Relation\x12.\n\x07\x65ntity1\x18\x01 \x01(\x0b\x32\x1d.watson_nlp_data_model.Entity\x12.\n\x07\x65ntity2\x18\x02 \x01(\x0b\x32\x1d.watson_nlp_data_model.Entity\x12\x41\n\x11relation_mentions\x18\x03 \x03(\x0b\x32&.watson_nlp_data_model.RelationMention\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.relation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RELATION']._serialized_start=145
  _globals['_RELATION']._serialized_end=352
# @@protoc_insertion_point(module_scope)
