# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.speaker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#watson_nlp_data_model.speaker.proto\x12\x15watson_nlp_data_model*+\n\x07Speaker\x12\t\n\x05UNSET\x10\x00\x12\n\n\x06\x43LIENT\x10\x01\x12\t\n\x05\x41GENT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.speaker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPEAKER']._serialized_start=62
  _globals['_SPEAKER']._serialized_end=105
# @@protoc_insertion_point(module_scope)
