# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.syntaxparser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(watson_nlp_data_model.syntaxparser.proto\x12\x15watson_nlp_data_model*\x8e\x01\n\x0cSyntaxParser\x12\x10\n\x0cSYNTAX_UNSET\x10\x00\x12\x13\n\x0fSYNTAX_TOKENIZE\x10\x01\x12\x13\n\x0fSYNTAX_SENTENCE\x10\x02\x12\x10\n\x0cSYNTAX_LEMMA\x10\x03\x12\x15\n\x11SYNTAX_DEPENDENCY\x10\x04\x12\x19\n\x15SYNTAX_PART_OF_SPEECH\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.syntaxparser_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNTAXPARSER']._serialized_start=68
  _globals['_SYNTAXPARSER']._serialized_end=210
# @@protoc_insertion_point(module_scope)
