# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.targetssentimentprediction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import aggregatedsentiment_pb2 as watson__nlp__data__model_dot_aggregatedsentiment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6watson_nlp_data_model.targetssentimentprediction.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a/watson_nlp_data_model.aggregatedsentiment.proto\"\xa6\x02\n\x1aTargetsSentimentPrediction\x12\x66\n\x13targeted_sentiments\x18\x01 \x03(\x0b\x32I.watson_nlp_data_model.TargetsSentimentPrediction.TargetedSentimentsEntry\x12\x39\n\x0bproducer_id\x18\x02 \x01(\x0b\x32$.caikit_data_model.common.ProducerId\x1a\x65\n\x17TargetedSentimentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.watson_nlp_data_model.AggregatedSentiment:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.targetssentimentprediction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _TARGETSSENTIMENTPREDICTION_TARGETEDSENTIMENTSENTRY._options = None
  _TARGETSSENTIMENTPREDICTION_TARGETEDSENTIMENTSENTRY._serialized_options = b'8\001'
  _globals['_TARGETSSENTIMENTPREDICTION']._serialized_start=174
  _globals['_TARGETSSENTIMENTPREDICTION']._serialized_end=468
  _globals['_TARGETSSENTIMENTPREDICTION_TARGETEDSENTIMENTSENTRY']._serialized_start=367
  _globals['_TARGETSSENTIMENTPREDICTION_TARGETEDSENTIMENTSENTRY']._serialized_end=468
# @@protoc_insertion_point(module_scope)
