# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.topic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import ngram_pb2 as watson__nlp__data__model_dot_ngram__pb2
from watson_nlp_data_model import topicphrase_pb2 as watson__nlp__data__model_dot_topicphrase__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!watson_nlp_data_model.topic.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a!watson_nlp_data_model.ngram.proto\x1a\'watson_nlp_data_model.topicphrase.proto\"\x88\x02\n\x05Topic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0c\n\x04size\x18\x03 \x01(\r\x12,\n\x06ngrams\x18\x04 \x03(\x0b\x32\x1c.watson_nlp_data_model.NGram\x12\x34\n\x08snippets\x18\x05 \x03(\x0b\x32\".watson_nlp_data_model.TopicPhrase\x12\x35\n\tsentences\x18\x06 \x03(\x0b\x32\".watson_nlp_data_model.TopicPhrase\x12\x39\n\x0bproducer_id\x18\x07 \x01(\x0b\x32$.caikit_data_model.common.ProducerIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.topic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOPIC']._serialized_start=180
  _globals['_TOPIC']._serialized_end=444
# @@protoc_insertion_point(module_scope)
