# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.vectorizationprediction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import sparsematrix_pb2 as watson__nlp__data__model_dot_sparsematrix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3watson_nlp_data_model.vectorizationprediction.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a(watson_nlp_data_model.sparsematrix.proto\"\x87\x01\n\x17VectorizationPrediction\x12\x31\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32#.watson_nlp_data_model.SparseMatrix\x12\x39\n\x0bproducer_id\x18\x02 \x01(\x0b\x32$.caikit_data_model.common.ProducerIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.vectorizationprediction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORIZATIONPREDICTION']._serialized_start=164
  _globals['_VECTORIZATIONPREDICTION']._serialized_end=299
# @@protoc_insertion_point(module_scope)
