# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.vectorization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common import producerid_pb2 as caikit__data__model_dot_common_dot_producerid__pb2
from watson_nlp_data_model import sparsematrix_pb2 as watson__nlp__data__model_dot_sparsematrix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)watson_nlp_data_model.vectorization.proto\x12\x15watson_nlp_data_model\x1a)caikit_data_model.common.producerid.proto\x1a(watson_nlp_data_model.sparsematrix.proto\"\xfc\x01\n\rVectorization\x12\x31\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32#.watson_nlp_data_model.SparseMatrix\x12J\n\x0cvocab_to_idx\x18\x02 \x03(\x0b\x32\x34.watson_nlp_data_model.Vectorization.VocabToIdxEntry\x12\x39\n\x0bproducer_id\x18\x03 \x01(\x0b\x32$.caikit_data_model.common.ProducerId\x1a\x31\n\x0fVocabToIdxEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.vectorization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _VECTORIZATION_VOCABTOIDXENTRY._options = None
  _VECTORIZATION_VOCABTOIDXENTRY._serialized_options = b'8\001'
  _globals['_VECTORIZATION']._serialized_start=154
  _globals['_VECTORIZATION']._serialized_end=406
  _globals['_VECTORIZATION_VOCABTOIDXENTRY']._serialized_start=357
  _globals['_VECTORIZATION_VOCABTOIDXENTRY']._serialized_end=406
# @@protoc_insertion_point(module_scope)
