# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.viewproperty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from watson_nlp_data_model import viewpropertyvalue_pb2 as watson__nlp__data__model_dot_viewpropertyvalue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(watson_nlp_data_model.viewproperty.proto\x12\x15watson_nlp_data_model\x1a-watson_nlp_data_model.viewpropertyvalue.proto\"\xb8\x01\n\x0cViewProperty\x12J\n\x0c\x61ql_property\x18\x01 \x03(\x0b\x32\x34.watson_nlp_data_model.ViewProperty.AqlPropertyEntry\x1a\\\n\x10\x41qlPropertyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.watson_nlp_data_model.ViewPropertyValue:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.viewproperty_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _VIEWPROPERTY_AQLPROPERTYENTRY._options = None
  _VIEWPROPERTY_AQLPROPERTYENTRY._serialized_options = b'8\001'
  _globals['_VIEWPROPERTY']._serialized_start=115
  _globals['_VIEWPROPERTY']._serialized_end=299
  _globals['_VIEWPROPERTY_AQLPROPERTYENTRY']._serialized_start=207
  _globals['_VIEWPROPERTY_AQLPROPERTYENTRY']._serialized_end=299
# @@protoc_insertion_point(module_scope)
