# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watson_nlp_data_model.viewpropertyvalue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from watson_nlp_data_model import propertylistvaluebool_pb2 as watson__nlp__data__model_dot_propertylistvaluebool__pb2
from watson_nlp_data_model import propertylistvaluefloat_pb2 as watson__nlp__data__model_dot_propertylistvaluefloat__pb2
from watson_nlp_data_model import propertylistvalueint_pb2 as watson__nlp__data__model_dot_propertylistvalueint__pb2
from watson_nlp_data_model import propertylistvaluespan_pb2 as watson__nlp__data__model_dot_propertylistvaluespan__pb2
from watson_nlp_data_model import propertylistvaluestr_pb2 as watson__nlp__data__model_dot_propertylistvaluestr__pb2
from watson_nlp_data_model import span_pb2 as watson__nlp__data__model_dot_span__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-watson_nlp_data_model.viewpropertyvalue.proto\x12\x15watson_nlp_data_model\x1a\x31watson_nlp_data_model.propertylistvaluebool.proto\x1a\x32watson_nlp_data_model.propertylistvaluefloat.proto\x1a\x30watson_nlp_data_model.propertylistvalueint.proto\x1a\x31watson_nlp_data_model.propertylistvaluespan.proto\x1a\x30watson_nlp_data_model.propertylistvaluestr.proto\x1a watson_nlp_data_model.span.proto\"\xfd\x03\n\x11ViewPropertyValue\x12\x11\n\x07str_val\x18\x01 \x01(\tH\x00\x12\x13\n\tfloat_val\x18\x02 \x01(\x01H\x00\x12\x11\n\x07int_val\x18\x03 \x01(\x05H\x00\x12\x12\n\x08\x62ool_val\x18\x04 \x01(\x08H\x00\x12/\n\x08span_val\x18\x05 \x01(\x0b\x32\x1b.watson_nlp_data_model.SpanH\x00\x12\x43\n\x0clist_str_val\x18\x06 \x01(\x0b\x32+.watson_nlp_data_model.PropertyListValueStrH\x00\x12G\n\x0elist_float_val\x18\x07 \x01(\x0b\x32-.watson_nlp_data_model.PropertyListValueFloatH\x00\x12\x43\n\x0clist_int_val\x18\x08 \x01(\x0b\x32+.watson_nlp_data_model.PropertyListValueIntH\x00\x12\x45\n\rlist_bool_val\x18\t \x01(\x0b\x32,.watson_nlp_data_model.PropertyListValueBoolH\x00\x12\x45\n\rlist_span_val\x18\n \x01(\x0b\x32,.watson_nlp_data_model.PropertyListValueSpanH\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watson_nlp_data_model.viewpropertyvalue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIEWPROPERTYVALUE']._serialized_start=361
  _globals['_VIEWPROPERTYVALUE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
