
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T15:11:25+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "3c0d497fdf6f62381a4df062d4a500b561209b74",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
