
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-16T14:41:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1982970d4783f8d1b5a19fb6a248acf81854e411",
 "version": "0.3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
