
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T12:04:28-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c3e8cfc685e39b078233fe063d2b16825804d96",
 "version": "1.17.24.post0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
