# coding: utf-8

"""
    Snowflake Table API

    The Snowflake Table API is a REST API that you can use to access, update, and perform certain actions on Tables resource in a Snowflake database.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@snowflake.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import snowflake.core.table._generated
from snowflake.core.table._generated.models.table_object_parameters_model import TableObjectParametersModel  # noqa: E501
from snowflake.core.table._generated.rest import ApiException

class TestTableObjectParametersModel(unittest.TestCase):
    """TableObjectParametersModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TableObjectParametersModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableObjectParametersModel`
        """
        model = snowflake.core.table._generated.models.table_object_parameters_model.TableObjectParametersModel()  # noqa: E501
        if include_optional :
            return TableObjectParametersModel(
                data_rentention_time_in_days = 56, 
                max_data_extension_time_in_days = 56, 
                default_ddl_collation = ''
            )
        else :
            return TableObjectParametersModel(
        )
        """

    def testTableObjectParametersModel(self):
        """Test TableObjectParametersModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
