
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-17T11:50:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bf2f4cd1b334a3a05b97ee4668122f1c01d3302",
 "version": "1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
