
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T10:12:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "893cd3413141ff8b4d9f58fe5553b3fb9bf262c0",
 "version": "2023.11.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
