from fdsreader import Simulation
from theutil.models import Model

class FDSModel(Model, Simulation):
    """Represents a single FDS / PyroSim simulation and it's results

    Args:
        results_file_name (str): The basename of the .smv Results file generated by FDS
    """
    
    def __init__(self, results_file_name: str):
        
        Model.__init__(self, results_file_name, ".fds")
        Simulation.__init__(self, results_file_name)