
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-15T18:56:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c3746baeecf2ff3a0f5f7a049dcb22d3e6eab43",
 "version": "0.23.1.post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
