# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infoservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caikit_data_model.common.runtime import runtimeinforequest_pb2 as caikit__data__model_dot_common_dot_runtime_dot_runtimeinforequest__pb2
from caikit_data_model.common.runtime import runtimeinforesponse_pb2 as caikit__data__model_dot_common_dot_runtime_dot_runtimeinforesponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11infoservice.proto\x12\x13\x63\x61ikit.runtime.info\x1a\x39\x63\x61ikit_data_model.common.runtime.runtimeinforequest.proto\x1a:caikit_data_model.common.runtime.runtimeinforesponse.proto2\x8c\x01\n\x0bInfoService\x12}\n\x0eGetRuntimeInfo\x12\x34.caikit_data_model.common.runtime.RuntimeInfoRequest\x1a\x35.caikit_data_model.common.runtime.RuntimeInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infoservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFOSERVICE']._serialized_start=162
  _globals['_INFOSERVICE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
