
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T14:59:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aecdf7a6e4ee3ffff59ca35b2bfe329a46a69dfa",
 "version": "1.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
