
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-16T16:29:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b99cf06a0d3bf27cb5d2d03d52a285cc91cfb6f6",
 "version": "0.25.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
