from typing import List

class PyCreationError(Exception):
    ...

class SymbolTable:
    def __init__(self, symbols: str): ...
    def mudder(self, a:str, b:str, amount: int) -> List[str]: ...
    def mudder_one(self, a: str, b: str) -> str: ...
    def generate(self, amount: int) -> List[str]: ...

    @staticmethod
    def alphabet() -> 'SymbolTable': ...

    @staticmethod
    def base36() -> 'SymbolTable': ...

    @staticmethod
    def base62() -> 'SymbolTable': ...
