from typing import List, Optional

class PyCreationError(Exception): ...

class SymbolTable:
    def __init__(self, symbols: str): ...
    def mudder(self, amount: int, a: Optional[str], b: Optional[str]) -> List[str]: ...
    def mudder_one(self, a: Optional[str], b: Optional[str]) -> str: ...
    @staticmethod
    def alphabet() -> "SymbolTable": ...
    @staticmethod
    def base36() -> "SymbolTable": ...
    @staticmethod
    def base62() -> "SymbolTable": ...
    @staticmethod
    def hex() -> "SymbolTable": ...
