"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ChannelSide:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChannelSideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChannelSide.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOCAL: _ChannelSide.ValueType  # 0
    REMOTE: _ChannelSide.ValueType  # 1

class ChannelSide(_ChannelSide, metaclass=_ChannelSideEnumTypeWrapper): ...

LOCAL: ChannelSide.ValueType  # 0
REMOTE: ChannelSide.ValueType  # 1
global___ChannelSide = ChannelSide

class _ChannelState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChannelStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChannelState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Openingd: _ChannelState.ValueType  # 0
    ChanneldAwaitingLockin: _ChannelState.ValueType  # 1
    ChanneldNormal: _ChannelState.ValueType  # 2
    ChanneldShuttingDown: _ChannelState.ValueType  # 3
    ClosingdSigexchange: _ChannelState.ValueType  # 4
    ClosingdComplete: _ChannelState.ValueType  # 5
    AwaitingUnilateral: _ChannelState.ValueType  # 6
    FundingSpendSeen: _ChannelState.ValueType  # 7
    Onchain: _ChannelState.ValueType  # 8
    DualopendOpenInit: _ChannelState.ValueType  # 9
    DualopendAwaitingLockin: _ChannelState.ValueType  # 10
    ChanneldAwaitingSplice: _ChannelState.ValueType  # 11

class ChannelState(_ChannelState, metaclass=_ChannelStateEnumTypeWrapper): ...

Openingd: ChannelState.ValueType  # 0
ChanneldAwaitingLockin: ChannelState.ValueType  # 1
ChanneldNormal: ChannelState.ValueType  # 2
ChanneldShuttingDown: ChannelState.ValueType  # 3
ClosingdSigexchange: ChannelState.ValueType  # 4
ClosingdComplete: ChannelState.ValueType  # 5
AwaitingUnilateral: ChannelState.ValueType  # 6
FundingSpendSeen: ChannelState.ValueType  # 7
Onchain: ChannelState.ValueType  # 8
DualopendOpenInit: ChannelState.ValueType  # 9
DualopendAwaitingLockin: ChannelState.ValueType  # 10
ChanneldAwaitingSplice: ChannelState.ValueType  # 11
global___ChannelState = ChannelState

class _HtlcState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HtlcStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HtlcState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SentAddHtlc: _HtlcState.ValueType  # 0
    SentAddCommit: _HtlcState.ValueType  # 1
    RcvdAddRevocation: _HtlcState.ValueType  # 2
    RcvdAddAckCommit: _HtlcState.ValueType  # 3
    SentAddAckRevocation: _HtlcState.ValueType  # 4
    RcvdAddAckRevocation: _HtlcState.ValueType  # 5
    RcvdRemoveHtlc: _HtlcState.ValueType  # 6
    RcvdRemoveCommit: _HtlcState.ValueType  # 7
    SentRemoveRevocation: _HtlcState.ValueType  # 8
    SentRemoveAckCommit: _HtlcState.ValueType  # 9
    RcvdRemoveAckRevocation: _HtlcState.ValueType  # 10
    RcvdAddHtlc: _HtlcState.ValueType  # 11
    RcvdAddCommit: _HtlcState.ValueType  # 12
    SentAddRevocation: _HtlcState.ValueType  # 13
    SentAddAckCommit: _HtlcState.ValueType  # 14
    SentRemoveHtlc: _HtlcState.ValueType  # 15
    SentRemoveCommit: _HtlcState.ValueType  # 16
    RcvdRemoveRevocation: _HtlcState.ValueType  # 17
    RcvdRemoveAckCommit: _HtlcState.ValueType  # 18
    SentRemoveAckRevocation: _HtlcState.ValueType  # 19

class HtlcState(_HtlcState, metaclass=_HtlcStateEnumTypeWrapper): ...

SentAddHtlc: HtlcState.ValueType  # 0
SentAddCommit: HtlcState.ValueType  # 1
RcvdAddRevocation: HtlcState.ValueType  # 2
RcvdAddAckCommit: HtlcState.ValueType  # 3
SentAddAckRevocation: HtlcState.ValueType  # 4
RcvdAddAckRevocation: HtlcState.ValueType  # 5
RcvdRemoveHtlc: HtlcState.ValueType  # 6
RcvdRemoveCommit: HtlcState.ValueType  # 7
SentRemoveRevocation: HtlcState.ValueType  # 8
SentRemoveAckCommit: HtlcState.ValueType  # 9
RcvdRemoveAckRevocation: HtlcState.ValueType  # 10
RcvdAddHtlc: HtlcState.ValueType  # 11
RcvdAddCommit: HtlcState.ValueType  # 12
SentAddRevocation: HtlcState.ValueType  # 13
SentAddAckCommit: HtlcState.ValueType  # 14
SentRemoveHtlc: HtlcState.ValueType  # 15
SentRemoveCommit: HtlcState.ValueType  # 16
RcvdRemoveRevocation: HtlcState.ValueType  # 17
RcvdRemoveAckCommit: HtlcState.ValueType  # 18
SentRemoveAckRevocation: HtlcState.ValueType  # 19
global___HtlcState = HtlcState

@typing_extensions.final
class Amount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSAT_FIELD_NUMBER: builtins.int
    msat: builtins.int
    def __init__(
        self,
        *,
        msat: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["msat", b"msat"]) -> None: ...

global___Amount = Amount

@typing_extensions.final
class AmountOrAll(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    ALL_FIELD_NUMBER: builtins.int
    @property
    def amount(self) -> global___Amount: ...
    all: builtins.bool
    def __init__(
        self,
        *,
        amount: global___Amount | None = ...,
        all: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["all", b"all", "amount", b"amount", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["all", b"all", "amount", b"amount", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["amount", "all"] | None: ...

global___AmountOrAll = AmountOrAll

@typing_extensions.final
class AmountOrAny(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    ANY_FIELD_NUMBER: builtins.int
    @property
    def amount(self) -> global___Amount: ...
    any: builtins.bool
    def __init__(
        self,
        *,
        amount: global___Amount | None = ...,
        any: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["amount", b"amount", "any", b"any", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "any", b"any", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["amount", "any"] | None: ...

global___AmountOrAny = AmountOrAny

@typing_extensions.final
class ChannelStateChangeCause(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ChannelStateChangeCause = ChannelStateChangeCause

@typing_extensions.final
class Outpoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TXID_FIELD_NUMBER: builtins.int
    OUTNUM_FIELD_NUMBER: builtins.int
    txid: builtins.bytes
    outnum: builtins.int
    def __init__(
        self,
        *,
        txid: builtins.bytes = ...,
        outnum: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["outnum", b"outnum", "txid", b"txid"]) -> None: ...

global___Outpoint = Outpoint

@typing_extensions.final
class Feerate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SLOW_FIELD_NUMBER: builtins.int
    NORMAL_FIELD_NUMBER: builtins.int
    URGENT_FIELD_NUMBER: builtins.int
    PERKB_FIELD_NUMBER: builtins.int
    PERKW_FIELD_NUMBER: builtins.int
    slow: builtins.bool
    normal: builtins.bool
    urgent: builtins.bool
    perkb: builtins.int
    perkw: builtins.int
    def __init__(
        self,
        *,
        slow: builtins.bool = ...,
        normal: builtins.bool = ...,
        urgent: builtins.bool = ...,
        perkb: builtins.int = ...,
        perkw: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["normal", b"normal", "perkb", b"perkb", "perkw", b"perkw", "slow", b"slow", "style", b"style", "urgent", b"urgent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["normal", b"normal", "perkb", b"perkb", "perkw", b"perkw", "slow", b"slow", "style", b"style", "urgent", b"urgent"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["style", b"style"]) -> typing_extensions.Literal["slow", "normal", "urgent", "perkb", "perkw"] | None: ...

global___Feerate = Feerate

@typing_extensions.final
class OutputDesc(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    address: builtins.str
    @property
    def amount(self) -> global___Amount: ...
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        amount: global___Amount | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["amount", b"amount"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "amount", b"amount"]) -> None: ...

global___OutputDesc = OutputDesc

@typing_extensions.final
class RouteHop(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SHORT_CHANNEL_ID_FIELD_NUMBER: builtins.int
    FEEBASE_FIELD_NUMBER: builtins.int
    FEEPROP_FIELD_NUMBER: builtins.int
    EXPIRYDELTA_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    short_channel_id: builtins.str
    @property
    def feebase(self) -> global___Amount: ...
    feeprop: builtins.int
    expirydelta: builtins.int
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        short_channel_id: builtins.str = ...,
        feebase: global___Amount | None = ...,
        feeprop: builtins.int = ...,
        expirydelta: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["feebase", b"feebase"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["expirydelta", b"expirydelta", "feebase", b"feebase", "feeprop", b"feeprop", "id", b"id", "short_channel_id", b"short_channel_id"]) -> None: ...

global___RouteHop = RouteHop

@typing_extensions.final
class Routehint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOPS_FIELD_NUMBER: builtins.int
    @property
    def hops(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RouteHop]: ...
    def __init__(
        self,
        *,
        hops: collections.abc.Iterable[global___RouteHop] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hops", b"hops"]) -> None: ...

global___Routehint = Routehint

@typing_extensions.final
class RoutehintList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HINTS_FIELD_NUMBER: builtins.int
    @property
    def hints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Routehint]: ...
    def __init__(
        self,
        *,
        hints: collections.abc.Iterable[global___Routehint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hints", b"hints"]) -> None: ...

global___RoutehintList = RoutehintList

@typing_extensions.final
class TlvEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    type: builtins.int
    value: builtins.bytes
    def __init__(
        self,
        *,
        type: builtins.int = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type", b"type", "value", b"value"]) -> None: ...

global___TlvEntry = TlvEntry

@typing_extensions.final
class TlvStream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TlvEntry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___TlvEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___TlvStream = TlvStream
