
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-14T16:08:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ea766f9669e1f37295ab7d55240d2da4f6f521a",
 "version": "0.7.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
